### ISSUE TITLE
Street Fighter no sound, etc.

### ISSUE THREAD

**Issue by elco2** [ValadAmoleo/sf30ac-extractor#4]
No sound for Street Fighter in FB Neo. For completeness sake, here's the status of SF from the program itself. Everything else that says it should work does.
__________________________________________________________
Street Fighter is compatible with FB Neo

Street Fighter II The World Warrior is compatible with MAME-2001, MAME-2003, MAME-2003 Plus, MAME-2004, MAME-2005, MAME-2006, MAME-2007

Street Fighter II' Champion Edition is compatible with MAME-2001, MAME-2003, MAME-2003 Plus, MAME-2004, MAME-2005, MAME-2006, MAME-2007

Street Fighter II': Hyper Fighting is compatible with MAME-2001, MAME-2003, MAME-2003 Plus, MAME-2004, MAME-2005, MAME-2006, MAME-2007

Super Street Fighter II is compatible with Garbled graphics and broken audio, MAME-2001, MAME-2003, MAME-2003 Plus, MAME-2004, MAME-2005, MAME-2006, MAME-2007, MAME-2008, MAME-2009

Super Street Fighter II Turbo is compatible with Garbled graphics, MAME-2001, MAME-2003, MAME-2003 Plus, MAME-2004, MAME-2005, MAME-2006, MAME-2007, MAME-2008, MAME-2009

Super Street Fighter II Turbo (MAME 2010) is compatible with Garbled graphics, MAME-2010

Street Fighter III: New Generation is compatible with FB Neo

Street Fighter III: 2nd Impact is compatible with FB Neo

Street Fighter III: 3rd Strike is compatible with FB Neo

**Comment by elco2** [comment]
upon closer inspection the sound does work, it's just the intro sound for breaking the wall is missing. Not a big deal overall.

**Comment by elco2** [comment]
SSFII did not open for me in mame 2003 (inc. plus) but did in 2010 (garbled) I did not try the other mame versions on the list.

**Comment by elco2** [comment]
Possible solutions may exist at [https://github.com/0xZERO3/sf30thac_tool](url) , which is supposed to build super street fighter II Turbo &  Street Fighter Alpha 3. However its extractor is lacking files that appear in the eprom builder... most notably some "jr" files. The wydD extractor did not have them either. However this Valad extractor had one jr file for SFA3. Not quite good enough for a final build, but maybe enough clues are around.

**Comment by ValadAmoleo** [comment]
Sorry about not responding to this any earlier, I thought I'd get notifications when issues are opened but I didn't.

So Street Fighter actually verifies with FB Neo as being 100% correct.  So I can only assume that the sound missing is due to FB Neo itself or the sound isn't there to begin with.

ssf2u and ssf2tu are still incompatible.  Their inclusion in the code is more me showing my working in case anybody is looking along similar lines.

I'll have to take a deeper look at that link you've provided.  A brief glance over it seems like the CPS2 decoding is the same as what I'm doing for the CPS1 decoding.  While their CPS1 decoding is different.  This is likely due to differences in the preceding steps.  If I can figure that out it should unlock the remaining games to us.

**Comment by ValadAmoleo** [comment]
If you agree with the Street Fighter findings, we can close this issue. I've opened a separate one regarding CPS2 support.
